My ArrayList
yuriy-tsarenko/java_professional pull request #10
Opened 2021-03-19 16:33 UTC by CherednichenkoNikita

2021-03-21 11:41 UTC, ochedenis requested changes

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/Main.java
> +        }
For print you list at console just realize method toString.

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/MyAbstractList.java
> +public abstract class MyAbstractList<T> implements Iterable<T> {
interface MyAbstractList<T> extends Iterable<T>

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/MyArrayList.java
> +    private Object[] array = new Object[INIT_SIZE];
private T[] array = (T[]) new Object[INIT_SIZE];

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/MyArrayList.java
> +        Object[] newArray = new Object[newLength];
T[] newArray = (T[]) new Object[newLength];

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/MyArrayList.java
> +            resize(array.length * 2);
java code conventions
    if (pointer == array.length - 1) {
            resize(array.length * 2);
     }

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/MyArrayList.java
> +        for (int i = 0; i < pointer; i++)
java code conventions:
        for (int i = 0; i < pointer; i++) {
              action.accept(elementAt(objects, i));
        }

2021-03-21 11:41 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/myArrayList/MyArrayList.java
> +                    pointer + 1 - indexOf(element));
Make "if" like it requires java code conventions.

2021-04-02 11:22 UTC, yuriy-tsarenko approved these changes

2021-04-02 11:26 UTC, merged