HOMEWORK-1: homework_4
yuriy-tsarenko/java_professional pull request #16
Opened 2021-03-22 20:11 UTC by CherednichenkoNikita

renamed branch

2021-03-22 21:37 UTC, ochedenis approved these changes, later dismissed

2021-03-22 21:37 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_4/task_2/WriteInteger.java
> +            writer.flush();
Try with resources automatically closed writer. A close will always also flush. So you don't need flush by hands.

2021-03-23 13:08 UTC, yuriy-tsarenko requested changes
Fix code according to comments

2021-03-23 13:08 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_4/task_1/Write.java
> +    static Logger logger = Logger.getLogger(Write.class.getName());
```suggestion
    static Logger logger = Logger.getLogger(Write.class);
```
Change it

2021-03-23 13:08 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_4/task_2/WriteInteger.java
> +            writer.flush();
A close will always also flush in FileOutputStream family, but it doesn't work with FileWriter family.

2021-04-02 11:30 UTC, merged