Homework-1:reflection_diledsys
yuriy-tsarenko/java_professional pull request #18
Opened 2021-03-23 13:44 UTC by diledsys

2021-03-23 22:11 UTC, ochedenis requested changes

2021-03-23 22:11 UTC, ochedenis commented on src/main/java/com/java_professional/diledsys/homework/reflexion/DiscoweryClass.java
> +        this.string = string;
Mb string = str?

2021-03-23 22:11 UTC, ochedenis commented on src/main/java/com/java_professional/diledsys/homework/reflexion/DiscoweryClass.java
> +class DiscoweryClass {
For what you need this class?

2021-03-23 22:11 UTC, ochedenis commented on src/main/java/com/java_professional/diledsys/homework/reflexion/EnteringData.java
> +        return null;
On future - try never return null at your code.

2021-03-23 22:11 UTC, ochedenis commented on src/main/java/com/java_professional/diledsys/homework/reflexion/EnteringData.java
> +        try {
Mb some: try with resources, or "BufferedReader.close()" at final?

2021-03-23 22:11 UTC, ochedenis commented on src/main/java/com/java_professional/diledsys/homework/reflexion/Reflexion.java
> +    private String modifierType(int mod) {
swichcase
case mod = 1 return public
case mod = 2 return private
PROTECTED = 4
STATIC = 8
FINAL = 16 
etc...

2021-03-23 22:11 UTC, ochedenis commented on src/main/java/com/java_professional/diledsys/homework/reflexion/Reflexion.java
> +            try {
vice versa
first try, then for
try {
    for (Field field : fields) {

2021-03-27 19:39 UTC, diledsys commented on src/main/java/com/java_professional/diledsys/homework/reflexion/DiscoweryClass.java
> +class DiscoweryClass {
для изучения, для рефлекции, он не участвует в логике

2021-03-27 19:41 UTC, diledsys commented on src/main/java/com/java_professional/diledsys/homework/reflexion/DiscoweryClass.java
> +        this.string = string;
это просто накиданый код, класс накидан для примера он так и называеться

2021-03-27 19:42 UTC, diledsys commented on src/main/java/com/java_professional/diledsys/homework/reflexion/Reflexion.java
> +    private String modifierType(int mod) {
ну как вариант, а так и ифки не плохо отработали

2021-03-27 19:43 UTC, diledsys commented on src/main/java/com/java_professional/diledsys/homework/reflexion/Reflexion.java
> +            try {
тут не понял что имееться в виду

2021-04-02 11:40 UTC, merged