homework 1
yuriy-tsarenko/java_professional pull request #3
Opened 2021-03-12 17:18 UTC by CherednichenkoNikita

2021-03-13 22:36 UTC, ochedenis submitted a review, later dismissed

2021-03-16 13:18 UTC, yuriy-tsarenko requested changes
Fix bugs according to my comments.
By the way, you have incorrect homework naming! Yo can read naming rules in slack.

2021-03-16 13:18 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_1/Product.java
> +import lombok.*;
replace this import with single class import

2021-03-16 13:18 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_1/Product.java
> +import java.util.*;
replace this import with single class import

2021-03-16 13:18 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_1/Product.java
> +public class Product {
Add the description of this task.

2021-03-16 13:18 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_1/Product.java
> +    }
Merge this methods into one

2021-03-22 11:21 UTC, yuriy-tsarenko requested changes
Fix gitignore and commit changes

2021-03-22 11:21 UTC, yuriy-tsarenko commented on java_professional.iml
> +</module>
Add this file to gitignore and remove from PR

2021-03-22 14:24 UTC, yuriy-tsarenko commented
fix build issues

2021-03-23 13:38 UTC, merged