Homework 2
yuriy-tsarenko/java_professional pull request #4
Opened 2021-03-13 19:33 UTC by CherednichenkoNikita

2021-03-13 22:47 UTC, ochedenis approved these changes, later dismissed

2021-03-13 22:47 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_2/LInkedListWithInteger.java
> +        }
you can just:
System.out.println(linkedList)

2021-03-13 22:47 UTC, ochedenis commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_2/LInkedListWithInteger.java
> +        }
you can just:
System.out.println(linkedList);

2021-03-16 13:27 UTC, yuriy-tsarenko requested changes
Fix bugs according to my comments.
By the way, you have incorrect homework branch naming! Yo can read naming rules in slack.

2021-03-16 13:27 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_1/DoubleValues.java
> +
Add the description of this task.

2021-03-16 13:27 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_1/DoubleValues.java
> +            System.out.println(s);
Shift your logic from main into special methods, main method body is too big

2021-03-16 13:27 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_1/DoubleValues.java
> +        }
It's bad practice, more better to code independent methods with return body

2021-03-16 13:27 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_2/LInkedListWithInteger.java
> +        }
It's bad practice, more better to code independent methods with return body

2021-03-16 13:27 UTC, yuriy-tsarenko commented on src/main/java/com/java_professional/cherednichenko/homework/lesson_2/task_2/Main.java
> +        list.getMinimum(linkedList);
Shift your logic from main into special methods, main method body is too big

2021-03-23 13:40 UTC, merged